= so25b: Sistemas Operacionais, 2º semestre, 2025
Benhur Stein <benhur+so25b@inf.ufsm.br>
v0.0, 1ago25

Página da disciplina de Sistemas Operacionais, segundo semestre de 2025.

[sidebar]
[no-bullet]
* ELC1080, DLSC/CT/UFSM, turmas de CC e Sistemas
* professor: Benhur Stein <benhur+so25b@inf.ufsm.br>
* terças e quintas, 10h30, sala 1309, anexo C do CT


== Desenvolvimento da disciplina

A comunicação entre o professor e os alunos será realizada por:

- encontros em sala de aula,
- esta página,
- e-mail (endereço acima),
- encontros agendados com o professor.

Esta página concentrará os assuntos vistos em aula, a descrição de exercícios e trabalhos, avaliações, etc.
Ela será aumentada/atualizada durante todo o semestre.
Ela é o canal mais oficial de informações sobre a disciplina, e deve ser consultada frequentemente pelo aluno (sugiro habilitar notificações de alteração do github).

A disciplina vai seguir de forma bastante próxima o assunto como ele é visto no livro
```
   Sistemas Operacionais Modernos
   Andrew S Tanenbaum
```

### Ementa

Ver https://www.ufsm.br/ementario/disciplinas/ELC1080/[aqui].

### Aulas

[%autowidth]
|===
|  # | data  | assunto

|  1 | 5ago  | apresentação
|  2 | 7ago  | introdução (1.1, 1.2)
|  3 | 12ago | código do t1
|  4 | 14ago | introdução (1.3)
|  5 | 19ago | introdução (1.5, 1.6)
|  6 | 21ago | processos (2.1)
|  7 | 26ago | sobre o t2
|===

### Avaliações

[%autowidth]
|===
| nome | data  | descrição

| t1   |       | Familiarização com o link:Trabalhos/t1[código].
| t2   |       | link:Trabalhos/t2[Processos, escalonamento]
|===

### Dados individuais

Dados sobre cada aluno estão na https://docs.google.com/spreadsheets/d/1BUePsr6-BJ0bhQDHo9YakGwzyZHLKRrVycYc7bjFJ6w/edit?usp=sharing[planilha].



